const actionTypes =
{
    LOG_IN: "LOG_IN",
    LOG_IN_FAIL: "LOG_IN_FAIL",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",

    LOG_OUT: "LOG_OUT",

    // register actions
    REGISTER_REQ: "REGISTER_REQ",
    REGISTER_FAIL: "REGISTER_FAIL",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",

    CHANGE_PASS_REQ: "CHANGE_PASS_REQ",
    CHANGE_PASS_FAIL: "CHANGE_PASS_FAIL",
    CHANGE_PASS_SUCCESS: "CHANGE_PASS_SUCCESS"
}
export default actionTypes;